[package]
name = "megra_rs"
version = "0.0.1"
authors = ["nik <nik@parkellipsen.de>"]
edition = "2018"
license = "GPL-3.0+"

[dependencies]
cpal = { path = "../thirdparty/cpal", features = ["jack"]}
anyhow = "1.0"
crossbeam = "0.8"
parking_lot = "0.11"
ruffbox_synth = { path = "../ruffbox-synth" }
nom = "6.0"
#vom_rs = { git = "https://gitlab.com/ellipsenpark/vom.rs" }
vom_rs = { path = "../vom.rs" }
rustyline = "6.3.0"
claxon = "0.4.3"
getopts = "0.2"
rand = "0.7"
egui = { path = "../thirdparty/egui/egui" }
egui_glium = { path = "../thirdparty/egui/egui_glium" }
epi = { path = "../thirdparty/egui/epi", features = ["persistence"]}
serde = { version = "1", features = ["derive"] }
dashmap = "4.0.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"
