[package]
name = "megra_rs"
version = "0.0.1"
authors = ["nik <nik@parkellipsen.de>"]
edition = "2018"
license = "GPL-3.0+"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
cpal = { path = "../thirdparty/cpal", features = ["jack"]}
anyhow = "1.0"
lazy_static = "1.4.0"
crossbeam = "0.7.3"
parking_lot = "0.11.0"
ruffbox_synth = { git = "https://github.com/the-drunk-coder/ruffbox-synth"}
nom = "6.0.0-alpha1"
vom_rs = { git = "https://gitlab.com/ellipsenpark/vom.rs" }
rustyline = "6.3.0"
claxon = "0.4.3" 